name: transcriptomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # R and Bioconductor
  - r-base>=4.2
  - bioconductor-deseq2
  - r-biocparallel
  
  # Core Python packages
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.11.0
  
  # Visualization
  - plotly>=5.18.0
  
  # Machine learning
  - scikit-learn>=1.3.0
  
  # R interface
  - rpy2>=3.5.0
  
  # Web framework
  - dash>=2.14.0
  
  # Development tools
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.0.0
  - flake8>=6.0.0
  - isort>=5.12.0
  
  # Pip packages (not in conda)
  - pip:
    - dash-bootstrap-components>=1.5.0
    - umap-learn>=0.5.0
    - goatools>=1.3.0
    - gseapy>=1.0.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - pyyaml>=6.0.0
    - joblib>=1.3.0
    - openpyxl>=3.1.0